# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.45.1"
"rocks-config.nvim" = "3.1.2"
"mason-lspconfig.nvim" = "1.32.0"
neorg = "9.3.0"
"oil.nvim" = "2.15.0"
"conform.nvim" = "9.0.0"
"diffview.nvim" = "scm"
"rocks-git.nvim" = "2.5.4"
neogit = "2.0.0"
nvim-web-devicons = "0.100"
"nightfox.nvim" = "3.10.0"
nvim-autopairs = "scm"
"rocks-lazy.nvim" = "1.2.2"
"nvim-tree.lua" = "1.6.0"
"lsp-zero.nvim" = "scm"
"comment.nvim" = "0.8.0"
"plenary.nvim"= "scm"
"bufferline.nvim" = "4.9.1"
nvim-cmp = "scm"
cmp-nvim-lsp = "scm"
luasnip = "2.4.0"
cmp-cmdline = "scm"
nvim-lspconfig = "2.3.0"
"lualine.nvim" = "scm"
"mason.nvim" = "1.11.0"
"which-key.nvim" = "3.17.0"
nvim-dap = "0.10.0"
nvim-dap-ui = "4.0.0"
nvim-dap-virtual-text = "scm"
nvim-dap-python = "scm"
nvim-lint = "scm"
"gitsigns.nvim"= "1.0.2"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.10.0"

[plugins."telescope.nvim"]
git = "nvim-telescope/telescope.nvim"
rev = "0.1.8"

[plugins."leap.nvim"]
git = "ggandor/leap.nvim"
rev = "897a9adbec7ac5d0900d4d13980c3f06c16b9092"

[plugins.vimtex]
git = "lervag/vimtex"
rev = "v2.16"

[plugins."copilot.vim"]
git = "github/copilot.vim"
rev = "v1.51.0"

[plugins."copilotchat.nvim"]
git = "copilotc-nvim/copilotchat.nvim"
rev = "v3.12.2"

[config]
plugins_dir = "plugins/"
auto_setup = false
