# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.46.1"
"rocks-config.nvim" = "3.1.2"
"mason-lspconfig.nvim" = "2.1.0"
neorg = "9.3.0"
"oil.nvim" = "2.15.0"
"conform.nvim" = "9.1.0"
"diffview.nvim" = "scm"
"rocks-git.nvim" = "2.5.7"
neogit = "3.0.0"
nvim-web-devicons = "0.100"
"nightfox.nvim" = "3.10.0"
nvim-autopairs = "scm"
"rocks-lazy.nvim" = "1.2.2"
"nvim-tree.lua" = "1.6.0"
"lsp-zero.nvim" = "scm"
"comment.nvim" = "0.8.0"
"plenary.nvim"= "scm"
"bufferline.nvim" = "4.9.1"
nvim-cmp = "scm"
cmp-nvim-lsp = "scm"
luasnip = "2.4.1"
cmp-cmdline = "scm"
nvim-lspconfig = "2.5.0"
"lualine.nvim" = "scm"
"mason.nvim" = "2.1.0"
nvim-dap = "0.10.0"
nvim-dap-ui = "4.0.0"
nvim-dap-virtual-text = "scm"
nvim-dap-python = "scm"
nvim-lint = "scm"
"gitsigns.nvim"= "1.0.2"
vim-floatterm = "scm"
"toggleterm.nvim" = "2.13.1"
nvim-highlight-colors = "scm"
"hardtime.nvim" = "1.2.0"
"flash.nvim" = "2.1.0"
nvim-treesitter-textobjects = "scm"
"noice.nvim" = "4.10.0"
"nui.nvim" = "0.4.0"
nvim-surround = "3.1.8"
"neoscroll.nvim" = "0.2.0"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.10.0"

[plugins."telescope.nvim"]
git = "nvim-telescope/telescope.nvim"
rev = "v0.2.1"

[plugins.vimtex]
git = "lervag/vimtex"
rev = "v2.17"

[plugins."copilot.vim"]
git = "github/copilot.vim"
rev = "v1.58.0"

[plugins."copilotchat.nvim"]
git = "copilotc-nvim/copilotchat.nvim"
rev = "v4.7.4"

[plugins.tagbar]
git = "preservim/tagbar"
rev = "v3.1.1"

[plugins."tiny-inline-diagnostic.nvim"]
git = "rachartier/tiny-inline-diagnostic.nvim"
rev = "9b55d36b797875b6e513f6bcc526e17cb9fe31f4"

[plugins."lean.nvim"]
git = "julian/lean.nvim"
rev = "v2025.10.1"

[plugins."smear-cursor.nvim"]
git = "sphamba/smear-cursor.nvim"
rev = "v0.6.0"

[plugins.vim-wakatime]
git = "https://github.com/wakatime/vim-wakatime.git"
rev = "11.3.0"

[config]
plugins_dir = "plugins/"
auto_setup = false
